// source/renderer/components/titlebar/index.tsx
import * as React from "react";

import "./index.scss";

export type TitleBarState = {
	focus: boolean,
	restore: boolean,
	fullscreen: boolean;
};

class TitleBar extends React.Component<TitleBarState> {
	public state: TitleBarState;
	constructor(properties: TitleBarState) {
		super(properties);
		this.state = { ...properties };
	}
	static getDerivedStateFromProps($new: TitleBarState, $old: TitleBarState) {
		return $new;
	}
	public render() {
		return (
			<section id="titlebar" class="contrast draggable">
				<button id="focus" class="un_draggable"
					onClick={() => {
						nw.Window.get().minimize();
					}}
					dangerouslySetInnerHTML={{ __html: require(`!html-loader!@/assets/icons/focus.svg`) }}>
				</button>
				<button id="restore" class="un_draggable"
					onClick={() => {
						if (!this.state.restore) {
							nw.Window.get().maximize();
						} else if (this.state.focus && !this.state.fullscreen) {
							nw.Window.get().restore();
						}
					}}
					dangerouslySetInnerHTML={{ __html: require(this.state.restore ? "!html-loader!@/assets/icons/minimize.svg" : "!html-loader!@/assets/icons/maximize.svg") }}>
				</button>
				<button id="close" class="un_draggable"
					onClick={() => {
						nw.Window.get().close();
					}}
					dangerouslySetInnerHTML={{ __html: require(`!html-loader!@/assets/icons/close.svg`) }}>
				</button>
			</section>
		);
	}
}
export default TitleBar;

// src/renderer/components/titlebar.vue
<template>
	<keep-alive>
		<header id="titlebar" class="contrast draggable">
			<button id="focus" class="none-draggable" @click="app.minimize()">
				<!--
				<object :data="require(`@/assets/focus.svg`).default" type="image/svg+xml"></object>
				-->
				<svg v-html="require(`!html-loader!@/assets/icons/focus.svg`)"></svg>
			</button>
			<button id="restore" class="none-draggable" @click="restore = !restore">
				<!--
				<object :data="require(`@/assets/minimize.svg`).default" type="image/svg+xml"></object>
				-->
				<svg v-html="require(`!html-loader!@/assets/icons/${restore ? `minimize` : `maximize`}.svg`)"></svg>
			</button>
			<button id="close" class="none-draggable" @click="app.close()">
				<!--
				<object :data="require(`@/assets/close.svg`).default" type="image/svg+xml"></object>
				-->
				<svg v-html="require(`!html-loader!@/assets/icons/close.svg`)"></svg>
			</button>
		</header>
	</keep-alive>
</template>
<script src="./titlebar.ts"></script>
<style scoped src="./titlebar.scss"></style>
