// src/renderer/app.vue
<template>
	<keep-alive>
		<main id="container">
			<titlebar></titlebar>
			<article id="content">
				<querybox></querybox>
				<treeview></treeview>
				<iterable></iterable>
			</article>
			<taskbar></taskbar>
		</main>
	</keep-alive>
</template>
<script src="./app.ts"></script>
<style src="./app.scss"></style>

// src/renderer/app.tsx
import * as React from "react";

import "./app.scss";

import ScrollBar from "@/renderer/components/scrollbar";
import TitleBar from "@/renderer/components/titlebar";
import QueryBox from "@/renderer/components/querybox";
import TreeView from "@/renderer/components/treeview";
import Iterable from "@/renderer/components/iterable";
import TaskBar from "@/renderer/components/taskbar";

import listener from "@/modules/listener";

export type AppState = {};

class App extends React.Component<AppState, any> {
	public state: AppState;
	constructor(properties: AppState) {
		super(properties);
		this.state = { ...properties };

		if (process.env.NODE_ENV === "development") {
			nw.Window.get().showDevTools();
		}
		listener.on("reload", () => {
			window.location.reload();
		});
	}

	public render(): JSX.Element {
		return (
			<main id="container">
				<TitleBar focus={false} restore={false} fullscreen={false}></TitleBar>
				<article id="content">
					<QueryBox></QueryBox>
					<TreeView></TreeView>
					<Iterable></Iterable>
					<ScrollBar></ScrollBar>
				</article>
				<TaskBar></TaskBar>
			</main>
		);
	}
}
export default App;
